export const metadata = {
  title: 'Skill Up',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;700;900&display=swap" rel="stylesheet"/>
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
      </head>
      <body style={{fontFamily: 'Work Sans'}}>
        {children}
      </body>
    </html>
  )
}
